[package]
name = "project3_cargo"
version = "0.1.0"
authors = ["ryota"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portaudio = "0.7.0"
hound = "3.4.0"
